### ISSUE TITLE
errors in server

### ISSUE THREAD

**Issue by pinakinathc** [rohitmanglik/data-enrichment#74]
debug errors in server.

**Comment by pinakinathc** [comment]
@shubhiD  can you please help me with this, understanding the issue.

**Comment by pinakinathc** [comment]
@shashwat-vik scrap_bangalore.csv is showing error.

`Current file is ./input/scrap_bangalore.csv


RUNNING AUTOCOMPLETE
STATE :  Karnataka
Traceback (most recent call last):
  File "geocodertest.py", line 270, in <module>
    f.process()
  File "geocodertest.py", line 90, in process
    self.autoComp.main(self.rows,state)
  File "/home/user/pinaki/data-enrichment/autoComplete.py", line 209, in main
    self._autoComplete(state)
  File "/home/user/pinaki/data-enrichment/autoComplete.py", line 247, in _autoComplete
    address = row['Name'] + ', ' + row['Pincode']
TypeError: cannot concatenate 'str' and 'NoneType' objects
`

**Comment by rohitmanglik** [comment]
@pinakinathc please test the fix and update the issue accordingly.

**Comment by pinakinathc** [comment]
present errors:

`Current file is ./input/scrap_bangalore.csv


RUNNING AUTOCOMPLETE
STATE :  Karnataka
Traceback (most recent call last):
  File "geocodertest.py", line 270, in <module>
    f.process()
  File "geocodertest.py", line 90, in process
    self.autoComp.main(self.rows,state)
  File "/home/user/pinaki/data-enrichment/autoComplete.py", line 209, in main
    self._autoComplete(state)
  File "/home/user/pinaki/data-enrichment/autoComplete.py", line 267, in _autoComplete
    address = row['Name'] + ', ' + row['City']
TypeError: cannot concatenate 'str' and 'NoneType' objects
`

**Comment by pinakinathc** [comment]
new errors:
`Traceback (most recent call last):
  File "geocodertest.py", line 270, in <module>
    f.process()
  File "geocodertest.py", line 91, in process
    self._addGeocoding()
  File "geocodertest.py", line 142, in _addGeocoding
    new_city = row["City"].title()
AttributeError: 'NoneType' object has no attribute 'title'
`

**Comment by pinakinathc** [comment]
errors in scrap_goa.csv
`Current file is ./input/scrap_goa.csv


RUNNING AUTOCOMPLETE
STATE :  Goa
####################
VERIFIED     :  42
NOT VERIFIED :  51
####################

UPDAING ADDRESS
viewports for  11
Traceback (most recent call last):
  File "geocodertest.py", line 276, in <module>
    f.process()
  File "geocodertest.py", line 90, in process
    self.autoComp.main(self.rows,state)
  File "/home/user/pinaki/data-enrichment/autoComplete.py", line 212, in main
    self._remove_intermediate_duplicates()
  File "/home/user/pinaki/data-enrichment/autoComplete.py", line 438, in _remove_intermediate_duplicates
    hsh = self.rhash(row)
  File "/home/user/pinaki/data-enrichment/autoComplete.py", line 432, in rhash
    k+=str(row.get(i)).lower().strip()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 13: ordinal not in range(128)
`

**Comment by shashwat-vik** [comment]
Ignore two repetitive commits happened above.  bc38e28 is the concluding one.

**Comment by shashwat-vik** [comment]
Its will still show error, but now with function 'safe_dec_enc()'.
Will commit, after testing the fix.

**Comment by pinakinathc** [comment]
@rohitmanglik @shashwat-vik there are no errors in sulekha_other_temp. Checked all files.

**Comment by rohitmanglik** [comment]
Greate 👍
